# Generated by Django 6.0.5 on 2026-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_image', models.URLField()),
                ('p_desc', models.TextField()),
                ('p_category', models.CharField()),
                ('p_price', models.FloatField()),
            ],
        ),
    ]
